### ISSUE TITLE
PEP8 compliance

### ISSUE THREAD

**Issue by boarik** [omergertel/pyformance#63]
Thanks for this library!

I've gone over the code base and noticed diversions from the recommended PEP8 standard. A few stuff are more critical than others for readability and code cleanliness.

I thought of applying an automatic code formatter to this code such as [black](https://github.com/ambv/black), what are your thoughts @omergertel ?

**Comment by omergertel** [comment]
I think it might be overkill, but since running it and seeing what happens is simple enough, would you be kind enough to open a PR so we can see the amount of changes?

I'm generally for auto formatters, but I'm not working with Python currently, so I don't want to add complexity to the product. This means I'd love to fix what we have, but I'm hesitant to add it as part of the CI.

**Comment by boarik** [comment]
Done #64 .
Note I used the 100 chars line length variant, and included the core, test and example modules in the auto format.

Cheers

**Comment by omergertel** [comment]
Closed by #64
